### ISSUE TITLE
#error This version (2.x) of the Intercom iOS SDK supports iOS 7.0 upwards.

### ISSUE THREAD

**Issue by hussfelt** [asku/cordova-intercom#1]
We just tested this out and getting the above error.

Unclear why it thinks we're running <  iOS 7.0 in the emulator?
Are we doing anything wrong?

**Comment by joshdover** [comment]
Is your deployment target in the project settings set to 7.0 or higher?

**Comment by hussfelt** [comment]
Hey @joshdover!

Thanks, yeah - I found the same thing, so it's not related to cordova-intercom - closing this! :-)

Just as a sidenote, for anyone else experiencing this:
https://issues.apache.org/jira/browse/CB-7118
http://ezosaleh.com/adjust-ios-deployment-target-with-cordova-hooks-nodejs

Still a bit unclear on how to change this, @joshdover - any insights?

```<preference name="deployment-target" value="7.0" />``` ?

**Comment by hussfelt** [comment]
@joshdover Letting you close if you have any insights to leave behind :)

**Comment by hussfelt** [comment]
I can confirm that the above solved my issue!

**Comment by joshdover** [comment]
Good to hear!
