### ISSUE TITLE
Support for setting push token

### ISSUE THREAD

**Issue by elliotstokes** [asku/cordova-intercom#10]
Docs say 

In order to enable your users receive push notifications from Intercom via the Intercom SDK, you must register the device token of your user in the standard didRegisterForRemoteNotificationsWithDeviceToken: method:

- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
    if (deviceToken != nil) {
        [Intercom setDeviceToken:deviceToken];
    }
}

Im using the push plugin in cordova and have a device token so I'm assuming it would just be a matter of one js method and one obj c call in the background.

Looks like the api would need bumping up from 2.0.7 to 2.2 as well.

**Comment by joshdover** [comment]
Closed by #11
