### ISSUE TITLE
ios build failed

### ISSUE THREAD

**Issue by Mishit07** [asku/cordova-intercom#12]
Plugins/co.asku.cordova.intercom/Intercom.h:10:2: error: This version (2.x) of the Intercom iOS SDK supports iOS 7.0 upwards.
#error This version (2.x) of the Intercom iOS SDK supports iOS 7.0 upwards.
 ^
1 error generated.

** BUILD FAILED **
The following build commands failed:

**Comment by jtreanor** [comment]
Hi @Mishit07 

I am one of the mobile engineers at Intercom. We recommend that you use the official Intercom plugin [here](https://github.com/intercom/intercom-cordova).

The error is because Intercom for iOS requires iOS 7 or higher. To enforce this in your app, add this to your `config.xml`:

```
...
<platform name="ios">
        ...
        <preference name="deployment-target" value="7.0" />
        ...
 </platform>
...
```

**Comment by Mishit07** [comment]
Hello James. I am using the official intercom plugin now. I added the preference value for deployment target. But I am getting below error. Do you think I need to update anything ? 


#error This version (2.3.2) of Intercom for iOS supports iOS 7.0 upwards.
 ^
1 error generated.

** BUILD FAILED **

The following build commands failed:
	CompileC build/Sequr\ Kiwi.build/Debug-iphonesimulator/Sequr\ Kiwi.build/Objects-normal/i386/IntercomBridge.o Sequr\ Kiwi/Plugins/cordova-plugin-intercom/IntercomBridge.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error code 65 for command: xcodebuild with args: -xcconfig,/Users/Mishi/kiwi/sequr-kiwi-mobile/platforms/ios/cordova/build-debug.xcconfig,-project,Sequr Kiwi.xcodeproj,ARCHS=i386,-target,Sequr Kiwi,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/Mishi/kiwi/sequr-kiwi-mobile/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/Mishi/kiwi/sequr-kiwi-mobile/platforms/ios/build/sharedpch
ERROR building one of the platforms: Error: /Users/Mishi/kiwi/sequr-kiwi-mobile/platforms/ios/cordova/build: Command failed with exit code 2
You may not have the required environment or OS to build this project
Error: /Users/Mishi/kiwi/sequr-kiwi-mobile/platforms/ios/cordova/build: Command failed with exit code 2
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:134:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)


My system information is 

Your system information:
Cordova CLI: 5.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.0.0-rc.0
Ionic CLI Version: 1.6.4
Ionic App Lib Version: 0.3.8
ios-deploy version: 1.5.0 
ios-sim version: 3.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.7
Xcode version: Xcode 6.4 Build version 6E35b

**Comment by Mishit07** [comment]
Thanks James. After adding the deployment target and re-generating the platform this issue got resolved.
