### ISSUE TITLE
Package using old version of SDK, latest 2.2

### ISSUE THREAD

**Issue by hussfelt** [asku/cordova-intercom#2]
Is there any reason that this package is behind a couple of versions?

**Comment by joshdover** [comment]
No reason, just haven't updated it. The intercom team tends to move pretty quickly. Feel free to submit a PR, otherwise I'll get an update out this week.

**Comment by hussfelt** [comment]
@joshdover I really tried! ;-) ObjC is not my backyard... :) I actually tried upgrading yesterday, but hit some api-changes that broke the current setup.

Think I got passed the most things, but never really understood the error-callbacks, and why they didn't work with the new api-version...

Sorry for not being more helpful, thanks for sharing an awesome package! :-)

**Comment by joshdover** [comment]
Closed by #11
