### ISSUE TITLE
Not including keys at install in favor of config

### ISSUE THREAD

**Issue by hussfelt** [asku/cordova-intercom#4]
Trying to automate the install-process of plugins, it would be nice to add the keys after the installation if possible!

**Comment by joshdover** [comment]
Cordova doesn't have great support for something like this. At AskU, we
have templated out the config.xml and Info.plist files with a grunt build
step that generates the correct versions of the files we need for each app
when we build it. A custom solution like this in your project would
probably work.

This isn't a common use case so I don't intend on supporting it at the
plugin level.

**Comment by hussfelt** [comment]
Sounds like something I am trying to do... :)
I mean to have the config-details in the config.xml, is that not what you mean as well?

I mean - if not passing them at the installation point of the plugin in favour of ad-hearing to the config.xml I could automate the plugin-installation for each platform-add on all our developer-stations.

This is a hook I am currently having:

```
#!/usr/bin/env node
 
//this hook installs all your plugins
 
// add your plugins to this list--either 
// the identifier, the filesystem location 
// or the URL
var pluginlist = [
    "org.apache.cordova.statusbar",
    "org.apache.cordova.console",
    "org.apache.cordova.splashscreen",
    //"co.asku.cordova.intercom"
];
 
// no need to configure below
 
var fs = require('fs');
var path = require('path');
var sys = require('sys')
var exec = require('child_process').exec;
 
function puts(error, stdout, stderr) {
    sys.puts(stdout)
}
 
pluginlist.forEach(function(plug) {
    exec("cordova plugin add " + plug, puts);
});
```

**Comment by joshdover** [comment]
Since this is a special use case (and I assume you either figured it out or don't need it anymore), I'm closing this issue for now. Feel free to add more comments if you are still having trouble with this.

**Comment by hussfelt** [comment]
@joshdover No problem - we never got to do the Intercom test-implementation, but we're coming back to it soon.

When we do, I might look into helping out with this again!

Thanks Josh!
